#!/usr/bin/env php
<?php


use App\App;
use App\Core\Repository;
use App\Quote;

require __DIR__ . '/vendor/autoload.php';

require "helpers.php";

$repoData=require 'repositoryData.php';

Repository::bind('nav',$repoData['nav']);

Repository::bind('fastTypes',$repoData['fastTypes']);

$quotes=new Quote();

$quotes->getOne();

$app=new App(new Quote());

$app->run();










