#!/usr/bin/env php
<?php


use App\App;
use App\Core\Repository;

require __DIR__ . '/vendor/autoload.php';

require "helpers.php";

$repoData=require 'repositoryData.php';

Repository::bind('nav',$repoData['nav']);

Repository::bind('fastTypes',$repoData['fastTypes']);



// dd(Repository::get('properties'));


$app=new App();

$app->run();










